### PR TITLE
Proposal: Rest/Spread Properties

### PR DESCRIPTION
**Pull request by jamiebuilds**
re: #119

This is PR to discuss the AST for the "Rest/Spread Properties" proposal currently at Stage 3

```js
let { ...BindingRest } = { ...SpreadElement };
```

Changes:
- ~~Introduced new `BindingRest` node which accepts an `Expression` as `expression`~~
- ~~Added `BindingRest` to the `properties` of `ObjectBinding`~~
- ~~Added `SpreadElement` to the `properties` of `ObjectExpression`~~
- Added optional `rest` property to `ObjectBinding` which accepts a `BindingIdentifier`
- Added optional `rest` property to `ObjectAssignmentTarget` which accepts a `SimpleAssignmentTarget`

### CODE REVIEW

**Comment by bakkot** [comment]
Is there a reason for a new node type for `BindingRest`, rather than mirroring [the `ArrayBinding` case](https://github.com/shapesecurity/shift-spec/blob/5ec1b2d48b3d2458b9d1aa435933c1ce6cc549c3/spec.idl#L150)? I'd've gone with

```diff
interface ObjectBinding : Node {
  attribute BindingProperty[] properties;
+  attribute BindingIdentifier? rest;
};
```

This would enforce that there is at most one rest property, and not require a new node type. (Separately, I went with `BindingIdentifier` instead of `IdentifierExpression`, to match other bindings.)

---

This change also needs to handle the assignment target case - I'd go with

```diff
interface ObjectAssignmentTarget : Node {
  attribute AssignmentTargetProperty[] properties;
+  attribute SimpleAssignmentTarget? rest;
};
```

`SimpleAssignmentTarget` covers both `a` and `a.b`, as it should here:

- `({...a} = {})` and `({...a.b} = {})` are legal
-  `({...{}} = {})` and `({...[]} = {})` are not
- `let {...a} = {}` is legal
- `let {...a.b} = {}`, `let {...{}) = {}`, and `let {...[]} = {}` are not.

---

`SpreadElement` change seems good to me.

**Comment by jamiebuilds** [comment]
Right, for some reason I had been operating under the assumption that there could be multiple rest elements like there could be multiple spread, which makes no sense.

In `ObjectAssignmentTarget.rest`, instead of `SimpleAssignmentTarget` why not use `AssignmentTargetIdentifier`?

**Comment by bakkot** [comment]
> In `ObjectAssignmentTarget.rest`, instead of `SimpleAssignmentTarget` why not use `AssignmentTargetIdentifier`?

Because `({...a.b} = {})` is legal.

**Comment by jamiebuilds** [comment]
Oh right, I misunderstood

**Comment by michaelficarra** [comment]
Implemented in #135.

**Pull request closed without merging**
