### PR TITLE
split CompoundAssignmentExpression out of AssignmentExpression

### PR DESCRIPTION
**Pull request by michaelficarra**
:relieved:

### CODE REVIEW

**Comment by ikarienator** [comment]
Nice! :+1:

**Comment by ikarienator** [comment]
Care for porting it to es6 branch?

**Comment by michaelficarra** [comment]
I would love to, but isn't it locked? @jsoverson

**Comment by jsoverson** [comment]
es6 spec should be locked and backwards incompatible changes even from that should be minimized. With the specs targeting a yearly cycle, it's going to be much harder to stomach breaking changes going forward.

**Pull request merged**
