### PR TITLE
add optional tag to TemplateString

### PR DESCRIPTION
**Pull request by michaelficarra**

### CODE REVIEW

**Comment by michaelficarra** [comment]
Ping @ssrh @ikarienator.

**Comment by ikarienator** [comment]
I don't think this is right. I think we should have a TemplateCallExpression here.

**Comment by michaelficarra** [comment]
And what does that get us over this?

**Comment by ikarienator** [comment]
The semantics and precedence differences suggest that they are different things.

**Comment by ikarienator** [comment]
Please rebase.

**Pull request merged**
